version: '3.4'

services:
  guardian:
    image: ${DOCKER_REGISTRY-}guardian
    build:
      context: .
      dockerfile: Guardian/Dockerfile

  guardian.logging.api:
    image: ${DOCKER_REGISTRY-}guardianloggingapi
    build:
      context: .
      dockerfile: Guardian.Microservices/Guardian.Logging.Api/Dockerfile
